cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "anyenv"
brew "bat"
brew "direnv"
brew "docker"
brew "fzf"
brew "ghq"
brew "git"
brew "jq"
brew "mitmproxy"
brew "nkf"
brew "openssl"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

cask "chrysalis"
cask "discord"
cask "docker"
cask "epic-games"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "omnifocus"
cask "visual-studio-code"
cask "1password"
