add_newline = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[kubernetes]
disabled = false
style = "blue bold"
format = '[($symbol$context\($namespace\))]($style)'
